# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For 7447k,=o=o=/o*= see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Package Release

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Comma-separated list of packages to override default ("@ixo/oracles-chain-client,@ixo/oracles-client-sdk")'
        required: false
        default: "@ixo/logger,@ixo/oracles-chain-client,@ixo/oracles-client-sdk,@ixo/oracles-events"
        type: string

jobs:
  publish-npm:
    # needs: [build, versioning]
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.0
      - uses: actions/setup-node@v3
        with:
          node-version: 22.17.0
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies pnpm
        run: pnpm install --frozen-lockfile
      - name: Build packages
        run: |
          FILTERS=""
          IFS=',' read -ra PACKAGES <<< "${{ github.event.inputs.packages }}"
          for pkg in "${PACKAGES[@]}"; do
            FILTERS="$FILTERS --filter=$pkg"
          done
          pnpm build $FILTERS
      - name: Publish packages
        run: |
          FILTERS=""
          IFS=',' read -ra PACKAGES <<< "${{ github.event.inputs.packages }}"
          for pkg in "${PACKAGES[@]}"; do
            FILTERS="$FILTERS --filter=$pkg"
          done
          pnpm publish $FILTERS
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
